import { BudgetPeriod } from "@/types/budget";

// ─────────────────────────────────────────────────────────────────────────────
// 🛠️  STUB MODE — flip to `true` to use mock data instead of live Firestore
// ─────────────────────────────────────────────────────────────────────────────
export const USE_STUB = false;

/** Rich mock hierarchy: Period → Income nodes → Expense nodes */
export const STUB_DATA: BudgetPeriod[] = [
    {
        id: "stub-period-1",
        title: "August 1 – 15, 2026",
        income: 35000,
        date: "Aug 1, 2026",
        dateMs: new Date("2026-08-01").getTime(),
        added_by: "Rian",
        order: 0,
        subBudgets: [
            {
                id: "stub-income-1",
                title: "Salary",
                type: "income",
                amount: 25000,
                spent: undefined,
                date: "Aug 1, 2026",
                dateMs: new Date("2026-08-01").getTime(),
                added_by: "Rian",
                periodId: "stub-period-1",
                parentId: null,
                order: 0,
                subBudgets: [
                    {
                        id: "stub-expense-1",
                        title: "Groceries",
                        type: "expense",
                        spent: 5000,
                        date: "Aug 3, 2026",
                        dateMs: new Date("2026-08-03").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-1",
                        parentId: "stub-income-1",
                        order: 0,
                        subBudgets: [],
                    },
                    {
                        id: "stub-expense-2",
                        title: "Restaurant",
                        type: "expense",
                        spent: 2000,
                        date: "Aug 7, 2026",
                        dateMs: new Date("2026-08-07").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-1",
                        parentId: "stub-income-1",
                        order: 1,
                        subBudgets: [],
                    },
                    {
                        id: "stub-expense-3",
                        title: "Transport",
                        type: "expense",
                        spent: 1500,
                        date: "Aug 10, 2026",
                        dateMs: new Date("2026-08-10").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-1",
                        parentId: "stub-income-1",
                        order: 2,
                        subBudgets: [],
                    },
                ],
            },
            {
                id: "stub-income-2",
                title: "Incentives",
                type: "income",
                amount: 10000,
                spent: undefined,
                date: "Aug 1, 2026",
                dateMs: new Date("2026-08-01").getTime(),
                added_by: "Rian",
                periodId: "stub-period-1",
                parentId: null,
                order: 1,
                subBudgets: [
                    {
                        id: "stub-expense-4",
                        title: "Shopping",
                        type: "expense",
                        spent: 3000,
                        date: "Aug 5, 2026",
                        dateMs: new Date("2026-08-05").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-1",
                        parentId: "stub-income-2",
                        order: 0,
                        subBudgets: [],
                    },
                    {
                        id: "stub-expense-5",
                        title: "Utilities",
                        type: "expense",
                        spent: 1200,
                        date: "Aug 12, 2026",
                        dateMs: new Date("2026-08-12").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-1",
                        parentId: "stub-income-2",
                        order: 1,
                        subBudgets: [],
                    },
                ],
            },
        ],
    },
    {
        id: "stub-period-2",
        title: "July 16 – 31, 2026",
        income: 28000,
        date: "Jul 16, 2026",
        dateMs: new Date("2026-07-16").getTime(),
        added_by: "Rian",
        order: 1,
        subBudgets: [
            {
                id: "stub-income-3",
                title: "Salary",
                type: "income",
                amount: 22000,
                spent: undefined,
                date: "Jul 16, 2026",
                dateMs: new Date("2026-07-16").getTime(),
                added_by: "Rian",
                periodId: "stub-period-2",
                parentId: null,
                order: 0,
                subBudgets: [
                    {
                        id: "stub-expense-6",
                        title: "Groceries",
                        type: "expense",
                        spent: 4500,
                        date: "Jul 18, 2026",
                        dateMs: new Date("2026-07-18").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-2",
                        parentId: "stub-income-3",
                        order: 0,
                        subBudgets: [],
                    },
                    {
                        id: "stub-expense-7",
                        title: "Internet Bill",
                        type: "expense",
                        spent: 1800,
                        date: "Jul 20, 2026",
                        dateMs: new Date("2026-07-20").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-2",
                        parentId: "stub-income-3",
                        order: 1,
                        subBudgets: [],
                    },
                ],
            },
            {
                id: "stub-income-4",
                title: "Freelance",
                type: "income",
                amount: 6000,
                spent: undefined,
                date: "Jul 16, 2026",
                dateMs: new Date("2026-07-16").getTime(),
                added_by: "Rian",
                periodId: "stub-period-2",
                parentId: null,
                order: 1,
                subBudgets: [
                    {
                        id: "stub-expense-8",
                        title: "Coffee Runs",
                        type: "expense",
                        spent: 800,
                        date: "Jul 22, 2026",
                        dateMs: new Date("2026-07-22").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-2",
                        parentId: "stub-income-4",
                        order: 0,
                        subBudgets: [],
                    },
                    {
                        id: "stub-expense-9",
                        title: "Subscriptions",
                        type: "expense",
                        spent: 650,
                        date: "Jul 25, 2026",
                        dateMs: new Date("2026-07-25").getTime(),
                        added_by: "Rian",
                        periodId: "stub-period-2",
                        parentId: "stub-income-4",
                        order: 1,
                        subBudgets: [],
                    },
                ],
            },
        ],
    },
];
